[package]
name = "nautilus-slack"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Slack integration adapter for the Nautilus trading engine"
categories.workspace = true
keywords.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[lib]
name = "nautilus_slack"
crate-type = ["rlib", "cdylib"]

[features]
python = [
  "nautilus-common/python",
  "nautilus-core/python",
  "nautilus-model/python",
  "nautilus-network/python",
  "pyo3",
  "pyo3-async-runtimes",
  "pyo3-stub-gen",
]
extension-module = [
  "python",
  "pyo3/extension-module",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
nautilus-common = { workspace = true, features = ["live"] }
nautilus-core = { workspace = true }
nautilus-live = { workspace = true, optional = true }
nautilus-model = { workspace = true }
nautilus-network = { workspace = true }
nautilus-serialization = { workspace = true, features = [
  "arrow",
], optional = true }
nautilus-system = { workspace = true, optional = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
reqwest.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
url = { workspace = true }
zeroize = { workspace = true }

pyo3 = { workspace = true, optional = true }
pyo3-async-runtimes = { workspace = true, optional = true }
pyo3-stub-gen = { workspace = true, optional = true }

[dev-dependencies]
axum = { workspace = true }
proptest = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }

